name: macos
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
on: 
  workflow_run:
    workflows: [AutoTag]
    types: [completed]
  workflow_dispatch:
  # push:
  #   branches:
  #     - dev
  #     - master
  #     # - staged
  #   paths-ignore:
  #     - 'docs/**'
  #     - ".github/**"
  #     - "howto/**"
  #     - "*.md"
  #     - ".clang-format"
  # pull_request:
  #   branches:
  #     - dev
  #     - master
  #     # - staged
  #   paths-ignore:
  #     - 'docs/**'
  #     - ".github/**"
  #     - "howto/**"
  #     - "*.md"
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15,macos-11.0]
        qt_ver: [5.15.2]
        qt_arch: [clang_64]
    env:
      targetName: GoldenDict
      version: 22.2.alpha

    steps:
      # macos 11.0 默认环境变了,要指定
      - name: prepare env
        if: ${{ matrix.os == 'macos-11.0' }}
        run: |
          softwareupdate --all --install --force
          sudo xcode-select --print-path
          sudo xcode-select --switch /Library/Developer/CommandLineTools    
          # brew install qt@6   
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        # if: ${{ matrix.qt_ver == '5.15.2' }}
        with:
          version: ${{ matrix.qt_ver }}
          cached: 'false'
          modules: qtwebengine
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

          
      - name: build macos
        run: |
          brew install opencc
          qmake CONFIG+=release   CONFIG+=zim_support   CONFIG+=chinese_conversion_support
          make 
      # 打包
      - name: package
        run: |
          # 拷贝依赖
          macdeployqt ${targetName}.app -qmldir=. -verbose=1 -dmg
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short=8 HEAD)"    
          echo "::set-output name=release_date::$(date +'%Y%m%d')"    
          echo "::set-output name=release_time::$(date +'%H%M%S')"  
          echo "::set-output name=release_time_clock::$(date +'%H:%M:%S')"   

          previousTag=$(git tag --sort=-creatordate | sed -n 2p)
          echo "previousTag : $previousTag"
          
          CHANGELOG="$(git log --oneline --no-decorate $previousTag..HEAD)"
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          echo "::set-output name=COMMIT_SUMMARY::$(echo "$CHANGELOG")"           
      # tag 上传Release
      - name: uploadRelease
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.targetName }}.dmg
          asset_name: ${{ matrix.qt_ver }}-${{ env.targetName }}_${{ matrix.os }}_${{ steps.vars.outputs.sha_short }}.dmg
          tag: v${{env.version}}-${{ steps.vars.outputs.sha_short }}
          overwrite: true 
          release_name: win-ubuntu-macos-${{ github.ref_name }}-${{steps.vars.outputs.release_date}} 
          prerelease: true
          body: |
            release on date:      ${{steps.vars.outputs.release_date}} time: ${{steps.vars.outputs.release_time_clock}}  
            branch:               ${{ github.ref_name }}
            commit:               ${{ steps.vars.outputs.sha_short }} 
            Qt version:           ${{ matrix.qt_ver }} ${{ matrix.qt_arch }}
            Windows built with:   msvc64  Visual studio 2019
            ## goldendict.exe can not used alone 
            if you have a previous version. replace this maybe ok. if not ,download the whole bundle.

            AppImage built with:  Ubuntu-20.04 ,latest gcc
            macos built with:     macos-10.15,macos-11.0,clang_64
            This is a prerelease version ,auto build by github action. use on your on risk:-)   

            CHANGES:
            ${{ steps.vars.outputs.COMMIT_SUMMARY }}            
